version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ~/postgres/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    network_mode: bridge
